### ISSUE TITLE
Inventory Import issue (R36RC4)

### ISSUE THREAD

**Issue by ihocking** [phreebooks/PhreeBooksERP#163]
Importing new items using Tools / Import-Export leaves some fields not displayed.
Clearing the cache seemed to work but did not on a repeat (or ever since). The fields were in the mysql Database but not displayed in Phreebooks. In this case they were Vendor (which was created prior to import), purchase description, item cost. Below is the file content, 1 line header, 1 line data:
SKU,Inactive,Type,ShortDescription,PurchaseDescription,SalesDescription,GLSalesAccount,GLInventoryAccount,GLCOGSAccount,SalesTaxable,PurchaseTaxable,ItemCost,CostMethod,FullPrice,ReorderQuantity,VendorID,LeadTime
TEST33APC8005C00,0,si,CLUTCH CABLE,LA8005C00,CLUTCH CABLE 63 1/4 S-S,4000,1200,5000,2,2,1.11,f,1.11,1,10001,80

**Comment by charles2** [comment]
I have tested this feature and it works as expected.

I am going to close this 'issue' as there has been no follow-up.

If anyone disagrees, you can re-open it.
