### ISSUE TITLE
Negative stock showing as "on hand"?

### ISSUE THREAD

**Issue by billj9000** [phreebooks/PhreeBooksERP#198]
Often we will invoice a customer for a "special order" item that is not currently in stock and only then (often after receipt of payment) will we raise a PO to order the item from a supplier. On submitting the invoice, the quantity in stock becomes negative. When I raise a PO, the item is shown as "on hand" when in fact we have none in stock.

My guess is that "on hand" is true if qty != 0 . It seems to me that it would make more sense for "on hand" only to be true if qty > 0 ?

**Comment by billj9000** [comment]
The particular SKU that prompted me to raise the issue is a "Stock Item".

**Comment by ReneKervezee** [comment]
Thanks for reporting the issue.
just updated the code.

**Comment by billj9000** [comment]
That appears to have fixed the problem. Thanks!
There appears to be a similar type of problem with filling a PO with items with low stock but I'll look into it further and raise a separate issue.

Closing this now.
