### ISSUE TITLE
receipt not printing 

### ISSUE THREAD

**Issue by ritesh80058** [phreebooks/PhreeBooksERP#199]
HI I using phreebooksR37RC1.I am not able to print receipt in pos.I tried and read all options.The printer name in till is also same as in print preferences.I even tested print in Firefox.Its printing well but not in phreebooks pos.My printer also accepts raw commands.When i make a payment and i click on pdf print icon nothing happens infact pop-up window disappears and window comes back to pos layout

**Comment by ReneKervezee** [comment]
Did you set the phreepos config option. Enable direct printing to true. And
is your receipt marked as sequential.
Op 12 jan. 2015 08:16 schreef "ritesh80058" <notifications@github.com> het
volgende:

**Comment by ritesh80058** [comment]
HI thanks a lot for such a quick response.Yes i do enabled direct printing true.And yes my receipt is marked as sequential.As i don't have any technical knowledge so am uploading screenshots of all settings in my computer as well as phreebooks.Please help me sir.
![00](https://cloud.githubusercontent.com/assets/10493767/5722326/17ff757c-9b61-11e4-9349-967b387cefec.jpg)
![0](https://cloud.githubusercontent.com/assets/10493767/5722303/16566c44-9b61-11e4-9aed-c8c5f2cfbc04.jpg)
![1](https://cloud.githubusercontent.com/assets/10493767/5722304/165c65cc-9b61-11e4-8515-24c74195948b.jpg)
![2](https://cloud.githubusercontent.com/assets/10493767/5722305/165f2e1a-9b61-11e4-8602-f91fccef3fb2.jpg)
![3](https://cloud.githubusercontent.com/assets/10493767/5722306/166499a4-9b61-11e4-8161-1c4c7771da61.jpg)
![4](https://cloud.githubusercontent.com/assets/10493767/5722307/166c6e04-9b61-11e4-933b-eacae716179c.jpg)
![5](https://cloud.githubusercontent.com/assets/10493767/5722308/16715540-9b61-11e4-8fe4-7c11f48cbb62.jpg)
![6](https://cloud.githubusercontent.com/assets/10493767/5722309/167612e2-9b61-11e4-8018-e70a6caf7374.jpg)
![7](https://cloud.githubusercontent.com/assets/10493767/5722310/16ad7818-9b61-11e4-82d2-0e2cbf45ec54.jpg)
![8](https://cloud.githubusercontent.com/assets/10493767/5722311/16be6b5a-9b61-11e4-958a-f6b474f7fe2d.jpg)
![9](https://cloud.githubusercontent.com/assets/10493767/5722312/16cc19d0-9b61-11e4-9b89-bc9e7e9952d6.jpg)
![10](https://cloud.githubusercontent.com/assets/10493767/5722313/16df00f4-9b61-11e4-8cd0-c6c4cda3a615.jpg)
![11](https://cloud.githubusercontent.com/assets/10493767/5722314/16e75574-9b61-11e4-8e78-b72b937aaf56.jpg)
![12](https://cloud.githubusercontent.com/assets/10493767/5722315/16ee3b6e-9b61-11e4-9f99-e917f86257c6.jpg)
![13](https://cloud.githubusercontent.com/assets/10493767/5722316/17331360-9b61-11e4-8761-2495cc32e67e.jpg)
![14](https://cloud.githubusercontent.com/assets/10493767/5722318/17500cf4-9b61-11e4-8c74-1a95253d4a02.jpg)
![15](https://cloud.githubusercontent.com/assets/10493767/5722319/175371d2-9b61-11e4-849a-34ca2c68d34d.jpg)
![16](https://cloud.githubusercontent.com/assets/10493767/5722320/17661ad0-9b61-11e4-9be8-ba048824b542.jpg)
![17](https://cloud.githubusercontent.com/assets/10493767/5722321/1774b82e-9b61-11e4-8302-2cb46ea9a7ea.jpg)
![18](https://cloud.githubusercontent.com/assets/10493767/5722322/17874944-9b61-11e4-9c19-1ecec664a6ec.jpg)
![19](https://cloud.githubusercontent.com/assets/10493767/5722323/179d608a-9b61-11e4-9b55-e1813f450568.jpg)
![20](https://cloud.githubusercontent.com/assets/10493767/5722324/17a9df86-9b61-11e4-8fe9-07fa04133d97.jpg)
![21](https://cloud.githubusercontent.com/assets/10493767/5722325/17ebe14c-9b61-11e4-9b82-49722b8d402a.jpg)

**Comment by ReneKervezee** [comment]
Did you allow the java applet to run.
This is required for direct printing.

If you than also set the (java in the windows configuration ) the option
'show console'.
Than You should see the java console after the applet is loaded and allowed
to run.

In this console you should see line and printer commands after you click
print.
You should also see it searching for a printer match.

I saw in your screen shots that you haven't enabled share your printer over
network.
This is really handy than two worksations can use 1 printer. But be sure
that the local name is the same as the network name otherwise it wouldn't
work.

I don't know if you printer supports printing a logo( logo has to be stored
on your printer) If it does i am running a local version that supports logo
printing.
It still has to be incorporated

**Comment by ritesh80058** [comment]
HI thanks a lot for such a quick response.Yes i do enabled direct printing true.And yes my receipt is marked as sequential.As i don't have any technical knowledge so am uploading screenshots of all settings in my computer as well as phreebooks.Please help me sir.
![00](https://cloud.githubusercontent.com/assets/10493767/5722326/17ff757c-9b61-11e4-9349-967b387cefec.jpg)
![0](https://cloud.githubusercontent.com/assets/10493767/5722303/16566c44-9b61-11e4-9aed-c8c5f2cfbc04.jpg)
![1](https://cloud.githubusercontent.com/assets/10493767/5722304/165c65cc-9b61-11e4-8515-24c74195948b.jpg)
![2](https://cloud.githubusercontent.com/assets/10493767/5722305/165f2e1a-9b61-11e4-8602-f91fccef3fb2.jpg)
![3](https://cloud.githubusercontent.com/assets/10493767/5722306/166499a4-9b61-11e4-8161-1c4c7771da61.jpg)
![4](https://cloud.githubusercontent.com/assets/10493767/5722307/166c6e04-9b61-11e4-933b-eacae716179c.jpg)
![5](https://cloud.githubusercontent.com/assets/10493767/5722308/16715540-9b61-11e4-8fe4-7c11f48cbb62.jpg)
![6](https://cloud.githubusercontent.com/assets/10493767/5722309/167612e2-9b61-11e4-8018-e70a6caf7374.jpg)
![7](https://cloud.githubusercontent.com/assets/10493767/5722310/16ad7818-9b61-11e4-82d2-0e2cbf45ec54.jpg)
![8](https://cloud.githubusercontent.com/assets/10493767/5722311/16be6b5a-9b61-11e4-958a-f6b474f7fe2d.jpg)
![9](https://cloud.githubusercontent.com/assets/10493767/5722312/16cc19d0-9b61-11e4-9b89-bc9e7e9952d6.jpg)
![10](https://cloud.githubusercontent.com/assets/10493767/5722313/16df00f4-9b61-11e4-8cd0-c6c4cda3a615.jpg)
![11](https://cloud.githubusercontent.com/assets/10493767/5722314/16e75574-9b61-11e4-8e78-b72b937aaf56.jpg)
![12](https://cloud.githubusercontent.com/assets/10493767/5722315/16ee3b6e-9b61-11e4-9f99-e917f86257c6.jpg)
![13](https://cloud.githubusercontent.com/assets/10493767/5722316/17331360-9b61-11e4-8761-2495cc32e67e.jpg)
![14](https://cloud.githubusercontent.com/assets/10493767/5722318/17500cf4-9b61-11e4-8c74-1a95253d4a02.jpg)
![15](https://cloud.githubusercontent.com/assets/10493767/5722319/175371d2-9b61-11e4-849a-34ca2c68d34d.jpg)
![16](https://cloud.githubusercontent.com/assets/10493767/5722320/17661ad0-9b61-11e4-9be8-ba048824b542.jpg)
![17](https://cloud.githubusercontent.com/assets/10493767/5722321/1774b82e-9b61-11e4-8302-2cb46ea9a7ea.jpg)
![18](https://cloud.githubusercontent.com/assets/10493767/5722322/17874944-9b61-11e4-9c19-1ecec664a6ec.jpg)
![19](https://cloud.githubusercontent.com/assets/10493767/5722323/179d608a-9b61-11e4-9b55-e1813f450568.jpg)
![20](https://cloud.githubusercontent.com/assets/10493767/5722324/17a9df86-9b61-11e4-8fe9-07fa04133d97.jpg)
![21](https://cloud.githubusercontent.com/assets/10493767/5722325/17ebe14c-9b61-11e4-9b82-49722b8d402a.jpg)

**Comment by ritesh80058** [comment]
hello sir thanks a lot for your help my printer has started printing but still there is problem.I am getting this output as in screenshots after completion of print.I did it many time every time i am getting this output. 
![20150114_123520](https://cloud.githubusercontent.com/assets/10493767/5735308/0014511a-9bea-11e4-9007-94c2bfa73baf.jpg)
![1](https://cloud.githubusercontent.com/assets/10493767/5735317/24b09a60-9bea-11e4-9ecd-72e45a81b464.jpg)
![2](https://cloud.githubusercontent.com/assets/10493767/5735318/24b20f4e-9bea-11e4-8e57-653626539258.jpg)

**Comment by ReneKervezee** [comment]
What is the width of your receipt. 76mm
If you want the currency symbol to show you need to find the character table (printer manual) in witch your currency symbol is set then you need to look at what chr codes should be used in the header of your receipt.

What type of printer are you using. 
does is print both slip and receipt.

**Comment by ritesh80058** [comment]
hello sir i have removed symbol from currency and instead i used text for
this that is "Rs." and not output is pretty fine.But there is no space
between two receipts.My printer has the functionality of auto cutter
(Partial Cut) but i do not know the codes to be entered in till.My printer
uses esc/pos language.But i do  not know how to execute it.The code for
partial cut mentioned is "gs v" and "esc m" .Nothing more i know.I want to
know what exact codes i need to enter in till for paper cutting may the
screenshot would help.

**Comment by ritesh80058** [comment]
hi sir can you one thing please suggest me a printer model which has been tested with known codes and other configurations i will purchase that printer.I want a printer that can print bills as well as other reports

**Comment by ritesh80058** [comment]
i also want to sync it to my opencart based website

**Comment by ReneKervezee** [comment]
All esc pos printers will work with the pos module.

You should enter the following.
29,86,27,109

Provided that letters are lower case. If you want to look at other codes
have a look at this page.
You need to use the first column.
http://www.asciitable.com/

There are no printers that handle both normal page formats (a4/letter ) and
also handle receipts.

I do use a Epson tm-j7000 it handles both slips and receipts. But it is not
suitable as a printer for reports and invoices.

**Comment by ReneKervezee** [comment]
this is a screenshot of my till settings.
![screenshot](https://cloud.githubusercontent.com/assets/5244442/5837537/4f75f2f4-a180-11e4-9103-3f615ca6beb1.jpg)

this is a photo of my reciept. to give you a example
![dsc06154](https://cloud.githubusercontent.com/assets/5244442/5837547/7506a8a6-a180-11e4-9b67-6f1162f99a2d.JPG)

**Comment by charles2** [comment]
Hi Ritesh,

I have been following your 'issue' and reading with interest Rene's generous help extended to you (thank you, Rene).

Ritesh - what was the outcome of your issue?
Did you manage to get the POS module to do as you wanted?
Did you have to change POS printers?

Please feedback as much information as possible. This will help others, in turn.
