### ISSUE TITLE
hyperlink/Inventory Link field 

### ISSUE THREAD

**Issue by ReneKervezee** [phreebooks/PhreeBooksERP#203]
Hi all,
Setting up some custom fields I'm a bit perplexed how to use the hyperlink/Inventory Link field types as anything in these fields appear as plain text when I'm in my custom tab of the Inventory Manager?

This: http://wiki.xtronics.com/index.php/Phreebooks_Inventory seems to be the best description I can find but it does not go into detail about the types of how Inventory Links need to be created.

I've tried the drop down lists, checkbox and these appear as expected. I'm sure I am missing something obvious but some help would be appreciated. Regards

topic http://www.phreebooks.com/pb-forum/viewtopic.php?f=17&t=4156&p=14057#p14057

**Comment by phreesoft** [comment]
This is one of those features that I never implemented (but had good intentions). I intended this to be entered as a text field in the inventory manager and then place an icon next to the field that when clicked, takes you to a new page following the link. Right now, it just displays the url.

Probably should be and enhancement. I'll mark as such and put in for R4.0

--Dave
