### ISSUE TITLE
Image in Reports.

### ISSUE THREAD

**Issue by ReneKervezee** [phreebooks/PhreeBooksERP#204]
hi,
i want to know, how to display images in reports, rather than just a name of images like in inventory list report i have added column Image, it just fetch the name from the inventory table but i want to display images corresponds to sku if have any to customer easy access

topic http://www.phreebooks.com/pb-forum/viewtopic.php?f=13&t=4042

**Comment by phreesoft** [comment]
Printing images is not available in the current version. I don't even know if it is possible with the way reports are generated. This would need to be a new feature.  --Dave
