### ISSUE TITLE
error when installing release 4.0

### ISSUE THREAD

**Issue by shamzcc** [phreebooks/PhreeBooksERP#223]
hi 
im getting this error when trying to install release 4.0 any ideas
Warning: Invalid argument supplied for foreach() in /srv/www/htdocs/work/web/trunk/modules/phreeform/defaults.php on line 314

Fatal error: Class 'core\classes\messageStack' not found in /srv/www/htdocs/work/web/trunk/install/pages/main/pre_process.php on line 56

Warning: require(../includes/db/mysql/query_factory.php): failed to open stream: No such file or directory in /srv/www/htdocs/work/web/trunk/install/pages/main/pre_process.php on line 179

Fatal error: require(): Failed opening required '../includes/db/mysql/query_factory.php' (include_path='.:/usr/share/php5:/usr/share/php5/PEAR') in /srv/www/htdocs/work/web/trunk/install/pages/main/pre_process.php on line 179

**Comment by phreesoft** [comment]
PhreeBooks R4.0 is not ready for release, it is in development on GitHub and should not be considered anywhere close to prime time. Rene is leading the development, for updated status you need to contact him.

David Premo
PhreeSoft
E: dave.premo@phreesoft.com
M: 720-837-3142
