### ISSUE TITLE
online spreadsheets module,

### ISSUE THREAD

**Issue by alvin101** [phreebooks/PhreeBooksERP#227]
@ReneKervezee what is the chance to get a spreadsheet module?

https://github.com/Spreadsheets/WickedGrid

**Comment by charles2** [comment]
What is wrong with using a stand-alone spreadsheet?

Are you thinking about integration in some way?

The advantage isn't immediately apparent to me.

**Comment by alvin101** [comment]
Just having all your doc's in one place, one login for your business.  Google does a fine job, and I use them, but I do not trust them, they have screwed me before.  I would use a standalone system if I could find one. wickedgrid is not designed to run standalone...  Shared spreadsheets are used a lot in many business. Not thinking of integration.

**Comment by charles2** [comment]
OK, I now see what you mean. I also see the huge advantages of collaborative spreadsheets - however this is a HUGE project. I have come across one:
https://ethercalc.org/

and here are some other non-Google Docts web-spreadsheets :
http://visop-dev.com/Project+jQuery.sheet     jQuery.sheet. (TWiki plugin)
http://dhtmlx.com/docs/products/dhtmlxSpreadsheet/    dhtmlx Spreadsheet (Wordpress plugin)
http://www.zkoss.org/product/zkspreadsheet     ZKspreadsheet
http://www.gelsheet.org/    Gelsheet (Wordpress, Joomla plugin)

**Comment by charles2** [comment]
Looking at this further - that first link visop-dev.com, which seems now dead was jQuery.sheet which is somehow related to your Wicked.sheet??

Have you set up a functioning Wicked.sheet instance on your server yet? This is THE test - I have found them to be very tricky for me (not very techy).
