### ISSUE TITLE
about pos printer

### ISSUE THREAD

**Issue by nextwebzone** [phreebooks/PhreeBooksERP#228]
dear, thanks for your wonderful software, i need to know any kind of pos printer machine will work with this pos system?
thanks.

**Comment by phreesoft** [comment]
I don’t have a list of printers, I believe that most will work but you need to set some control characters specific to the printer. 

David Premo, PhreeSoft
E: dave.premo@phreesoft.com
W: www.PhreeSoft.com

**Comment by nextwebzone** [comment]
dear thank you for your reply, i understand your comments. 
Please help me some more, i have Posiflex Aura PP6900 Thermal POS Printer and i think the control characters need to set in to the pos module or Point of Sale Administration->till setup and here:(Here you can add code to that should be in the header paper of the receipt.
Seperate the codes by a : and lines by a , like: 27:112:48:55:121,27:109
The codes are a numbers of the chr ie chr(13) is 13).

so, in my pos printer which control characters i will set? and how? what does it means: 27:112:48:55:121,27:109?
again thank you.

**Comment by phreesoft** [comment]
I do not use the POS module so my help is limited. Try contacting Rene as he has spent more time on this module. There may also be some help on the forum at phreesoft.com <http://phreesoft.com/>

David Premo, PhreeSoft
E: dave.premo@phreesoft.com
W: www.PhreeSoft.com

**Comment by ReneKervezee** [comment]
You can do al most anything with these codes but you need to look into the
documents of your printer. If it your printer supports esc/pos use Google
to find a esc/pos documentation. These codes are explained better in the
documents than I ever can.

Op 16 jan. 2017 19:31 schreef "nextwebzone" <notifications@github.com>:
