### ISSUE TITLE
date problem

### ISSUE THREAD

**Issue by nextwebzone** [phreebooks/PhreeBooksERP#229]
dear, i am from Bangladesh and i face a date problem:
at night at 12.00 am the old date didn't change, 
Example: say the whole day was 18/01/2017 and at night after 11:59 pm its mean at 12:00 am or 1:00 am or 2:00 am, (3am,4am,5am,6am,7am,8am) the date still 18/01/2017. it should be 19/01/2017.
when i trying to do any type of transaction like sale/purchase invoice, point of sale etc.
i logout  and login again, shut down my laptop, clear browser but still the problem.
please help me more.
thanks.

**Comment by phreesoft** [comment]
I am no longer supporting PhreeBooks but if memory serves me, you need to log out and back in to change the system date.

Dave

**Comment by nextwebzone** [comment]
thank you sir, but i didn't find the system date. where is it? and if you not supporting the PhreeBooks then is  the system has any problem or closed?

**Comment by nextwebzone** [comment]
sorry, i edit the comments.

**Comment by nextwebzone** [comment]
at 12.00 pm the date changed but it should be change 12.00 am.

**Comment by ReneKervezee** [comment]
Where is your server located? 
In the current version we use the server date & time settings. 
Will look into it some more for the next release.

**Comment by nextwebzone** [comment]
my server is hostgator.com and i upload  phreebooks software in http://kefcosales.com/erp2/
when i use phreebooks software in localhost the date & time is ok but when i use it in online live server the problem is occurred.
i think your system date is updated by the host and its country.
so, how can i solve the problem?
and how can i get the current version?

**Comment by nextwebzone** [comment]
sorry to say, i was wrong,  in localhost the date also wrong, it shows 1 day early date.
thank you.

**Comment by nextwebzone** [comment]
i used xampp server in my local machine, here date.timezone=Asia/Dhaka, so, the date is ok but when i run your software at hostgator server (online live server) the date shows 12 hours delay.
In your php script i see gen_locale_date($date), so, may be gen_locale_date function not working. i don't know, i m weak in coding. please you can help me.
thanks.

**Comment by nextwebzone** [comment]
may be problem solve, i just set= date_default_timezone_set('Asia/Dhaka'); in index.php.
