### ISSUE TITLE
Freight Tax Calculations 

### ISSUE THREAD

**Issue by lacylive** [phreebooks/PhreeBooksERP#232]
Hi,

I made the tax settings As shown in the images
Phreebooks Admin->Customer Tab
![1](https://cloud.githubusercontent.com/assets/28355243/25669078/28ee968e-3046-11e7-91cb-ffec49c02fc2.PNG)  

Phreebooks Admin->Sales Tax Rates Tab
![2](https://cloud.githubusercontent.com/assets/28355243/25669193/696cec10-3046-11e7-87b9-9590e3c02fc0.PNG)

And Now while placing the order
Tax Rate i have selected State Only for an item
![3](https://cloud.githubusercontent.com/assets/28355243/25669254/9e5bf574-3046-11e7-91c7-7d8e344c6b60.PNG)

![4](https://cloud.githubusercontent.com/assets/28355243/25669284/aef3d0f0-3046-11e7-8550-4d7f4f06be1a.PNG)

As i have selected State Only Tax, and also made no to shipping charge calculations in Sales tax Rate, It should not calculate the tax for Freight . But Still it calculates.

Is it a bug or am i doing wrong? Please Suggest

Thanks 
Lacy M

**Comment by bryandale** [comment]
I've never been able to get tax on shipping to work. It's probably a bug. As a work around I list freight as a separate sales item and chose the appropriate tax. 

Bryan

Urbanrider.ca

**Comment by lacylive** [comment]
@bryandale : Thanks for the round about solution. 
If someone guides me, i can solve this as i am a programmer.

**Comment by ReneKervezee** [comment]
So far it works as it should be.
if the freight is 10,- the local tax over it is 0,87.

If you want no tax over the freight change it in the first image to 'non' /
'no tax'

I am not sure if the option in the second image still is used.
could be with stacked taxes that it is used.
will put it on the bug list.

2017-05-03 17:55 GMT+02:00 lacylive <notifications@github.com>:

**Comment by ReneKervezee** [comment]
Just noticing it is already here.
As i am looking it appears that this isn't transported to the javascript and than in the calculations it isn't checked if something is shipping and /or if it should be taxed.

**Comment by lacylive** [comment]
@ReneKervezee you are right, actually first image settings is for the whole software and second image setting should over ride it if that tax has to be excluded which is not happening. Can you please guide me how to set it right? or is it just a java script error.... I am a novice in java script
