### ISSUE TITLE
Setting up Credit Limit on individual customer basis

### ISSUE THREAD

**Issue by lacylive** [phreebooks/PhreeBooksERP#235]
Now i can set up the credit limit once for all the customers. But i want to set up the credit limit for each customer separately. While placing the order there is a option called **'terms'** , a pop up opens up to fill payment terms with credit limit. But even if i change the limit here  (**http://localhost/phreebooks/index.php?module=contacts&page=popup_terms&type=c&form=orders&val=**), it wont takes. It still takes the credit limit defined under **Company->Module Admi istration->Phreebooks Module->Customer->Credit Limit**

Can somebody tell me, is it an issue or some jquery i need to upgrade?

**Comment by ReneKervezee** [comment]
Did you change the radio button from default payment method to a different option?

**Comment by lacylive** [comment]
I tried in default option and by selecting other option also. It is not checking even if the order exceeds. Please suggest me where to change as I need this option

**Comment by ReneKervezee** [comment]
replace the following function in the file modules/phreebooks/javascript/orders.js
around line 900.

with the following code.
`function updateTotalPrices() {
	console.log("running updateTotalPrices");
  var numRows = 0;
  var discount = parseFloat(cleanCurrency(document.getElementById('discount').value));
  if (isNaN(discount)) discount = 0;
  var discountPercent = parseFloat(cleanCurrency(document.getElementById('disc_percent').value));
  if (isNaN(discountPercent)) discountPercent = 0;
  var item_count       = 0;
  var shipment_weight  = 0;
  var subtotal         = 0;
  var taxable_subtotal = 0;
  var freight_def_tax = default_sales_tax;
  var lineTotal        = '';
  if (single_line_list == '1') {
	numRows = document.getElementById('item_table').rows.length;
  } else {
	numRows = document.getElementById('item_table').rows.length/2;
  }
  for (var i=1; i<numRows+1; i++) {
	switch (journalID) {
	  case  '3':
	  case  '4':
	  case  '9':
	  case '10':
   	    item_count      += document.getElementById('qty_'+i).value ? parseFloat(document.getElementById('qty_'+i).value) : 0;
  	    shipment_weight += document.getElementById('qty_'+i).value * document.getElementById('weight_'+i).value;
	    break;
	  case  '6':
	  case  '7':
	  case '12':
	  case '13':
	  case '18':
	  case '19':
	  case '20':
	  case '21':
   	    item_count      += document.getElementById('pstd_'+i).value ? parseFloat(document.getElementById('pstd_'+i).value) : 0;
  	    shipment_weight += document.getElementById('pstd_'+i).value * document.getElementById('weight_'+i).value;
	    break;
	  default:
	}
    lineTotal = parseFloat(cleanCurrency(document.getElementById('total_'+i).value));
  	if (document.getElementById('tax_'+i).value != '0') {
      tax_index = document.getElementById('tax_'+i).selectedIndex;
	  if (tax_index == -1) { // if the rate array index is not defined
		tax_index = 0;
		document.getElementById('tax_'+i).value = tax_index;
	  }
	  if (tax_before_discount == '0') { // tax after discount
        taxable_subtotal += lineTotal * (1-(discountPercent/100)) * (tax_rates[tax_index].rate / 100);
	  } else { 
        taxable_subtotal += lineTotal * (tax_rates[tax_index].rate / 100);
	  }
	  freight_def_tax = tax_index;
	}
	subtotal += lineTotal;
  }

  // recalculate discount
  discount = subtotal * (discountPercent/100);
  var strDiscount = new String(discount);
  document.getElementById('discount').value = formatCurrency(strDiscount);
  // freight
  var strFreight = cleanCurrency(document.getElementById('freight').value);
  var freight = parseFloat(strFreight);
  if (isNaN(freight)) freight = 0;
  strFreight = new String(freight);
  document.getElementById('freight').value = formatCurrency(strFreight);
  if (tax_freight != 0 && freight_def_tax != 0) for (keyVar in tax_rates) {
    if (tax_rates[keyVar].id == tax_freight) taxable_subtotal += parseFloat(freight) * tax_rates[keyVar].rate / 100;
  }

  var nst = new String(taxable_subtotal);
  document.getElementById('sales_tax').value = formatCurrency(nst);
  document.getElementById('item_count').value = item_count;
  document.getElementById('weight').value = shipment_weight;
  var st = new String(subtotal);
  document.getElementById('subtotal').value = formatCurrency(st);
  var new_total = subtotal - discount + freight + taxable_subtotal;
  var tot = new String(new_total);
  document.getElementById('total').value = formatCurrency(tot);
  console.log("JournalID = " +journalID+" applyCreditLimit = "+ applyCreditLimit);
  if (journalID == '12' && applyCreditLimit == '1') {
	  console.log("apply credit Limit check if total ("+new_total+") is bigger than ("+custCreditLimit+")");
	  if (new_total > custCreditLimit && document.getElementById('override_user').value == '') showOverride();
  } else {
    if (document.getElementById('tb_icon_save'))          document.getElementById('tb_icon_save').style.visibility          = "";
    if (document.getElementById('tb_icon_print'))         document.getElementById('tb_icon_print').style.visibility         = "";
    if (document.getElementById('tb_icon_post_previous')) document.getElementById('tb_icon_post_previous').style.visibility = "";
    if (document.getElementById('tb_icon_post_next'))     document.getElementById('tb_icon_post_next').style.visibility     = "";
  }
}`

**Comment by ReneKervezee** [comment]
function updateTotalPrices() {
	console.log("running updateTotalPrices");
  var numRows = 0;
  var discount = parseFloat(cleanCurrency(document.getElementById('discount').value));
  if (isNaN(discount)) discount = 0;
  var discountPercent = parseFloat(cleanCurrency(document.getElementById('disc_percent').value));
  if (isNaN(discountPercent)) discountPercent = 0;
  var item_count       = 0;
  var shipment_weight  = 0;
  var subtotal         = 0;
  var taxable_subtotal = 0;
  var freight_def_tax = default_sales_tax;
  var lineTotal        = '';
  if (single_line_list == '1') {
	numRows = document.getElementById('item_table').rows.length;
  } else {
	numRows = document.getElementById('item_table').rows.length/2;
  }
  for (var i=1; i<numRows+1; i++) {
	switch (journalID) {
	  case  '3':
	  case  '4':
	  case  '9':
	  case '10':
   	    item_count      += document.getElementById('qty_'+i).value ? parseFloat(document.getElementById('qty_'+i).value) : 0;
  	    shipment_weight += document.getElementById('qty_'+i).value * document.getElementById('weight_'+i).value;
	    break;
	  case  '6':
	  case  '7':
	  case '12':
	  case '13':
	  case '18':
	  case '19':
	  case '20':
	  case '21':
   	    item_count      += document.getElementById('pstd_'+i).value ? parseFloat(document.getElementById('pstd_'+i).value) : 0;
  	    shipment_weight += document.getElementById('pstd_'+i).value * document.getElementById('weight_'+i).value;
	    break;
	  default:
	}
    lineTotal = parseFloat(cleanCurrency(document.getElementById('total_'+i).value));
  	if (document.getElementById('tax_'+i).value != '0') {
      tax_index = document.getElementById('tax_'+i).selectedIndex;
	  if (tax_index == -1) { // if the rate array index is not defined
		tax_index = 0;
		document.getElementById('tax_'+i).value = tax_index;
	  }
	  if (tax_before_discount == '0') { // tax after discount
        taxable_subtotal += lineTotal * (1-(discountPercent/100)) * (tax_rates[tax_index].rate / 100);
	  } else { 
        taxable_subtotal += lineTotal * (tax_rates[tax_index].rate / 100);
	  }
	  freight_def_tax = tax_index;
	}
	subtotal += lineTotal;
  }

  // recalculate discount
  discount = subtotal * (discountPercent/100);
  var strDiscount = new String(discount);
  document.getElementById('discount').value = formatCurrency(strDiscount);
  // freight
  var strFreight = cleanCurrency(document.getElementById('freight').value);
  var freight = parseFloat(strFreight);
  if (isNaN(freight)) freight = 0;
  strFreight = new String(freight);
  document.getElementById('freight').value = formatCurrency(strFreight);
  if (tax_freight != 0 && freight_def_tax != 0) for (keyVar in tax_rates) {
    if (tax_rates[keyVar].id == tax_freight) taxable_subtotal += parseFloat(freight) * tax_rates[keyVar].rate / 100;
  }

  var nst = new String(taxable_subtotal);
  document.getElementById('sales_tax').value = formatCurrency(nst);
  document.getElementById('item_count').value = item_count;
  document.getElementById('weight').value = shipment_weight;
  var st = new String(subtotal);
  document.getElementById('subtotal').value = formatCurrency(st);
  var new_total = subtotal - discount + freight + taxable_subtotal;
  var tot = new String(new_total);
  document.getElementById('total').value = formatCurrency(tot);
  console.log("JournalID = " +journalID+" applyCreditLimit = "+ applyCreditLimit);
  if (journalID == '12' && applyCreditLimit == '1') {
	  console.log("apply credit Limit check if total ("+new_total+") is bigger than ("+custCreditLimit+")");
	  if (new_total > custCreditLimit && document.getElementById('override_user').value == '') showOverride();
  } else {
    if (document.getElementById('tb_icon_save'))          document.getElementById('tb_icon_save').style.visibility          = "";
    if (document.getElementById('tb_icon_print'))         document.getElementById('tb_icon_print').style.visibility         = "";
    if (document.getElementById('tb_icon_post_previous')) document.getElementById('tb_icon_post_previous').style.visibility = "";
    if (document.getElementById('tb_icon_post_next'))     document.getElementById('tb_icon_post_next').style.visibility     = "";
  }
}
