### ISSUE TITLE
Adding discount manually while adding line items

### ISSUE THREAD

**Issue by lacylive** [phreebooks/PhreeBooksERP#236]
I want to add the discount manually instead of calculating it on price basis. I have changed the code like this in 
modules/phreebooks/javascript/orders.js 
`cell  = '<input type="text" class="form-control" name="disc_'+rowCnt+'" id="disc_'+rowCnt+'" onchange="updateRowTotal('+rowCnt+', false)" size="3" maxlength="10" style="text-align:right" />';`

and also in modules/phreebooks/pages/orders/template_main.php
`echo '  <td>' . html_input_field('disc_' . $i, '', ' onchange="updateRowTotal(' . $i . ', false)" maxlength="10" style="text-align:right"') . '</td>' . chr(10);`

But it doesn't work. Can someone suggest me where to  change?

**Comment by ReneKervezee** [comment]
I am not sure what you changed and what you want to achieve

**Comment by lacylive** [comment]
Hi Rene,

Because of severe health issue i could not check the topics. This is not solved yet for me. 

While placing order/quote now the discount is calculating on the price we put, But i want to change it.  After putting discount percentage, it has to calculate unit price . For example

full price is 500
i put discount as 2
quantity 1

then it has to calculate unit price like 
`unitPrice = (full_price*qty) - ((full_price*qty)*(2/100))`

I have changed it. But while placing new quote/order i am getting this values, but while editing it is not showing discount percentage. I am not getting where i need to change

Here is my orders.js changed code

```
function updateRowTotal(rowCnt, useAjax) {
	var qty = 0;
    var discount = 0;
	//var unit_price = cleanCurrency(document.getElementById('price_'+rowCnt).value);
	var full_price = cleanCurrency(document.getElementById('full_' +rowCnt).value);
	var discount1 =  document.getElementById('disc_' +rowCnt).value;
	
	 
	switch (journalID) {
		case  '3':
		case  '4':
		case  '9':
		case '10': 
		  qty = parseFloat(document.getElementById('qty_'+rowCnt).value);
		  if (isNaN(qty)) qty = 0; // if blank or a non-numeric value is in the qty field, assume zero
		  break;
		case  '6':
		case  '7':
		case '12':
		case '13':
		case '18':
		case '19':
		case '21':
		case '20': 
		  qty = parseFloat(document.getElementById('pstd_'+rowCnt).value);
		  if (isNaN(qty)) qty = 0; // if blank or a non-numeric value is in the pstd field, assume zero
		  break;
		default:
	}
	
	var unit_price = full_price - (full_price* (discount1/100));
	document.getElementById('price_'+rowCnt).value = formatCurrency(unit_price);
	var total_line = unit_price * qty;
	var total_l = new String(total_line);
	
	document.getElementById('total_'+rowCnt).value = formatCurrency(total_l);
	// calculate discount
	if (full_price > 0) {
	  var discount = unit_price * qty;
	}
```

And both in orders.js and orders/template_main.php, i changed like this

 `echo '  <td>' . html_input_field('disc_' . $i, '', '" size="11" onchange="updateRowTotal(' . $i . ', true)" maxlength="10" style="text-align:right"') . '</td>' . chr(10);`

But on edit ,
in this part (orders.js)

 ```
 quantity  = $(this).find("qty").text();
	    	unitPrice = $(this).find("unit_price").text();
	      }
		  insertValue('id_' + jIndex,                $(this).find("id").text());
		  insertValue('item_cnt_' + jIndex,          $(this).find("item_cnt").text());
		  insertValue('so_po_item_ref_id_' + jIndex, $(this).find("so_po_item_ref_id").text());
		  insertValue('qty_' + jIndex,               quantity);
		  insertValue('pstd_' + jIndex,              $(this).find("pstd").text());
		  insertValue('sku_'  + jIndex,              $(this).find("sku").text());
		  insertValue('desc_'  + jIndex,             $(this).find("description").text());
		 // insertValue('proj_'  + jIndex,             $(this).find("proj_id").text());
		  insertValue('date_1_'  + jIndex,           $(this).find("date_1").text());
		  insertValue('acct_'  + jIndex,             $(this).find("gl_account").text());
		  insertValue('tax_'  + jIndex,              $(this).find("taxable").text());
		  insertValue('full_'  + jIndex,             $(this).find("full_price").text());
		  insertValue('weight_'  + jIndex,           $(this).find("weight").text());
		  insertValue('serial_'  + jIndex,           $(this).find("serialize").text());
		  insertValue('stock_'  + jIndex,            $(this).find("stock").text());
		  insertValue('inactive_'  + jIndex,         $(this).find("inactive").text());
		  insertValue('lead_' + jIndex,              $(this).find("lead").text());
		  insertValue('price_' + jIndex,             unitPrice);
		  insertValue('total_' + jIndex,             $(this).find("total").text());
```
i am not getting how i should reload unit price and discount percentage .

Please can you guide me in this? in our state, discount runs like this and it is very much crucial .
