### ISSUE TITLE
Custom Field Phreebooks Module

### ISSUE THREAD

**Issue by talkinggoat** [phreebooks/PhreeBooksERP#240]
I am trying to add a custom field, to the user's section, for sales people, that would restrict a sales person to displaying the data for their own accounts. That way, when they are in the invoicing, quoting, sales sections, they can't see what the other salespeople are posting/making. Is there any easy way to do this in the frontend or will I need to modify the backend?

**Comment by phreesoft** [comment]
In PhreeBooks 3.7, there is no way to add an extra field to the users section. This would be a code change.

Dave

**Comment by talkinggoat** [comment]
Thanks for responding, Dave. I managed to insert the checkbox and get it to post into the proper table, column and row. Here is the code I used:
modules/phreedom/pages/users/template_detail.php line 70

`<td><?php echo "Restrict to own Accounts? " . html_checkbox_field('restrict_account', '1', (($error && $_POST['restrict_account']) || $uInfo->restrict_account) ? true : false) ; ?></td>`

Next, I was planning on calling to the "dep_rep_id" key, in the database and using that to filter out the rows created by the while loop on line 57 of modules/contacts/pages/main/template_details.php with an if condition. Something to the effect of, "if restrict_account = 1 show only tables with dep_rep_id = 'current user's ID number'" else, run the normal while loop, already on line 57. 

I'm very new to php, though. Could you offer some suggestions?

**Comment by phreesoft** [comment]
You do realize that PhreeBooks R3.7 has been deprecated. I stopped supporting that version at the start of this year. I am working on a open source Bizuno library and WordPress plugin but had to do a big re-write to meet the WordPress guidelines. I don’t have a target date on the release but I’m hoping in the next few months.

In the mean time, I been away from PhreeBooks R3.7 for so long any advise I give would need testing first and there is no way I have the time for that, sorry.
Dave
