### ISSUE TITLE
Sales/Invoice page problem

### ISSUE THREAD

**Issue by nextwebzone** [phreebooks/PhreeBooksERP#241]
hello sir, hope you are fine. i faced a problem hope you will help me.
when i try to input more than 40 item in Sales/Invoice page and save then the message shows:
The total field was not set, this means the form was not submitted in full and the order cannot be posted properly. The most common solution to this problem is to set the max_input_vars above the standard 1000 in your php.ini configuration file.

i need to entry more than 100 item for one customer for 1 Invoice.

**Comment by phreesoft** [comment]
The error message says exactly what to do, your input is being truncated by your php settings.

David Premo, PhreeSoft
E: dave.premo@phreesoft.com
W: www.PhreeSoft.com
