### ISSUE TITLE
Can not install on PHP 7!! MySQLi integration required!

### ISSUE THREAD

**Issue by itskawsar** [phreebooks/PhreeBooksERP#244]
When trying to install this ERP on PHP 7, getting following error:

     Fatal error: Uncaught Error: Call to undefined function mysql_connect() in ~\PhreeBooksERP\trunk\includes\db\mysql\query_factory.php:32 Stack trace: #0 ~\PhreeBooksERP\trunk\install\pages\main\pre_process.php(182): queryFactory->connect('localhost', 'root', '', 'erp_phreebooks') #1 ~\PhreeBooksERP\trunk\install\index.php(23): require_once('C:\\xampp\\htdocs...') #2 {main} thrown in ~\PhreeBooksERP\trunk\includes\db\mysql\query_factory.php on line 32

This error because of MySQLi. PHP 7 dropped MySQL. Is there any plan to upgrade it to MySQLi?

**Comment by phreesoft** [comment]
PhreeBooks 4.0 is the only option but it has not been (or may never be) released. PhreeBooks R3.7 has been deprecated. Users are encouraged to sign up for a free Bizuno account at the [www.PhreeSoft.com](https://www.PhreeSoft.com) website.
