### ISSUE TITLE
Bizuno Ajax Error: SyntaxError: JSON.

### ISSUE THREAD

**Issue by alvin101** [phreebooks/PhreeBooksERP#249]
Bizuno ERP - Settings, General, My Business

Bizuno Ajax Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data -
Fatal error: Call to undefined function bizuno\portalUpdateBizID() in /*****/lib/controller/module/bizuno/admin.php on line 271

Status: parsererror

I do not see any characters out of line here?

**Comment by phreesoft** [comment]
Go to /portal/functions.php and add the following at the end:

function portalUpdateBizID() { }

I’ll update the repository.

Dave
