### ISSUE TITLE
Missing redirect...

### ISSUE THREAD

**Issue by alvin101** [phreebooks/PhreeBooksERP#251]
We seem to miss a redirect back to the login page. After some time the system logs you out, but instead of a redirect you get error messages like: {"html":"","message":{"error":[{"text":"You do not have permission to alter this information! [admin]"}]}} and Bad request!

**Comment by phreesoft** [comment]
The cookie times out after 8 hours. Is this about the time you are seeing this message? I cannot change the message but I think I can put in a redirect so that if the cookie expires, whatever page is being requested is replaced with the home page.

Dave

**Comment by phreesoft** [comment]
This will be fixed in the next release, 5.0.3.
