### ISSUE TITLE
Fatal error on line 54 in file /portal/view.php. Description: 0 - Cannot use string offset as an array

### ISSUE THREAD

**Issue by lankeeyankee** [phreebooks/PhreeBooksERP#253]
I deleted all files and uploaded the new files and get this error. Running on PHP 7.1

**Comment by phreesoft** [comment]
Put this line just before line 54 of file /portal/view.php and let me know what your results are.

`if (!empty($data['title']) && is_array($data['title'])) { die("title is an array and should be a string: ".print_r($data['title'], true)); }`

It will kill the script but I need to know if it is a code problem and it will point to where I need to look.

Dave

**Comment by lankeeyankee** [comment]
I get the same error, just one line down, nothing else reported.

**Comment by lankeeyankee** [comment]
Also, have the install in a subdirectory and not in site root in case that matters.

**Comment by phreesoft** [comment]
Replace the line above with:

`die("title is an array and should be a string: ".print_r(getModuleCache('bizuno', 'properties', 'title'), true));`

Post results here.

Dave

**Comment by lankeeyankee** [comment]
title is an array and should be a string: Bizuno ERP

**Comment by phreesoft** [comment]
OK, so that doesn't make much sense. Your server is complaining about an array but this is a string. The other choice is not catching the trap (first code attempt) so that's not it either.

**Comment by phreesoft** [comment]
Try this, line 35 of /view/main.php. Replace the line with:

`        $this->output = ['head'=>[],'jsHead'=>[],'body'=>'','jsBody'=>[],'jsReady'=>[],'jsResize'=>[],'raw'=>''];
`

Dave

**Comment by lankeeyankee** [comment]
That fixed it, thanks!
