### ISSUE TITLE
Bravo Dave Premo

### ISSUE THREAD

**Issue by charles2** [phreebooks/PhreeBooksERP#254]
I spent a few hours on Sunday playing with the PB5 demo and really like it.

I have written a little 'Bravo Dave P' post on the 'Koozali SME server' website:
https://forums.contribs.org/index.php/topic,53746.0.html

Thank you,
Charles

**Comment by phreesoft** [comment]
It’s good the hear form you Charles. The demo is the older release. I haven’t had the time to upgrade it to the latest level. 

I’m also slowly re-working the site updating the knowledge base and manual. Rene has vanished from the project and I now do this as a ‘hobby’ although 30-40 hours per week is quite a hobby. Nonetheless I’m flying solo at this time. 

Dave

**Comment by charles2** [comment]
I will email you
