### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by chazdiezal** [phreebooks/PhreeBooksERP#255]
The customers, vendors, inventory, banking, general ledger, and tools buttons have disappeared from the main dashboard.  Any suggestions on how to get them back?

**Comment by phreesoft** [comment]
Log out, if you can, and then clear your browser cache for a week. Reload the page and log back in. Clearing the cache will reload your settings.

If you are using Chrome, switch to FireFox. More reliable.

Dave

**Comment by chazdiezal** [comment]
Thanks Dave!  Clearing the cache solved the issue.
