### ISSUE TITLE
Contacts Import Issue

### ISSUE THREAD

**Issue by felsenstein** [phreebooks/PhreeBooksERP#257]
I've been working on importing my contacts using the template from the Module - Contacts screen.  At first I had trouble getting the contacts to load, but finally had success.

I can only get a contacts file to import as long as the file ends with something other than .CSV

I renamed the same exact same file several ways and as long as it doesn't end in .CSV it will load without a problem.  Any time the filename ends with .CSV I get a message box saying Unknown upload validation error.

Just thought this was odd behavior so I thought I'd report it.  The work around is easy, and worked fine otherwise.

**Comment by phreesoft** [comment]
This could be how you are generating your css file. I have a couple of things to try, either should work.

First, I am testing for .csv (lower case) filename extensions. If you change the extension to lower case, the .csv extension should work. I’ll make a code change to make the filename extension case insensitive.

Second, depending on the application building the file, the MIME type may not be specified properly. I am expecting the MIME type to be text/csv but some applications generate application/vnd.ms-excel and it fails my verification. Try Notepad++ on a PC or BBEdit on a mac.

Dave

**Comment by felsenstein** [comment]
I just went into file manager and changed the file extension, and it works fine now.  Didn't need to modify anything in the file itself.  Both an Excel csv and a notepad ++ file uploaded fine.

Thank you!
