### ISSUE TITLE
PhreeBooks Conversion Extension Issue

### ISSUE THREAD

**Issue by felsenstein** [phreebooks/PhreeBooksERP#258]
I've tried various methods to get the Phreebooks Conversion Extension to download using the 5.2.0 version, self hosted.  I did successfully setup the Phreesoft.com account in the setting tab under the Bizuno ERP - Settings, and I went online and "ordered" it.  I don't really need the Translator Extension, but tried to download that as well just to see what would happen, and get the same message.

If I copy and paste the link in the error message below directly into my web browser, it downloads an empty zip file.

Here is the error message:

There was a problem retrieving your extension, please contact PhreeSoft for assistance.
NOTICE [2] copy(https://www.phreesoft.com/wp-admin/admin-ajax.php?action=bizuno_ajax&p=myPortal/admin/loadExtension&mID=xfrPhreeBooks): failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - Line 156 in file \lib\controller\module\bizuno\settings.php

So far all my other testing has been successful.  Thank you again for all your hard work.

**Comment by phreesoft** [comment]
Give me a few days to play with this on my sandbox and see if I can find what’s going on.

Dave

**Comment by phreesoft** [comment]
I’m about to release a new version of PhreeBooks 5, probably tomorrow. I also verified with the new version that the download, install is working for the PhreeBooks conversion script. As there are no settings for this script, you will know if it is installed if a new tab shows in the Tools -> Import/Export page named PhreeBooks Conversion.

Dave

**Comment by felsenstein** [comment]
I installed the newest version.  When I click the green arrow to download, I get a different message now:
There was a problem retrieving your extension, please contact PhreeSoft for assistance.

I checked under Tools -> Import/Export just in case it would show up anyway, no luck.

I also tried different browsers in the off chance the browser was the issue, but get the same message.

Nothing else really stands out as being out of the ordinary.

**Comment by phreesoft** [comment]
So here’s the code that does the transfer:

            $source = "https://www.phreesoft.com/wp-admin/admin-ajax.php?action=bizuno_ajax&p=myPortal/admin/loadExtension&mID=$moduleID";
            $dest   = BIZUNO_DATA."temp/$moduleID.zip";
            copy ($source, $dest, $context);
            if (file_exists(BIZUNO_DATA."temp/$moduleID.zip")) {
                $io->folderDelete(BIZUNO_EXT.$moduleID); // remove all current contents
                $io->zipUnzip(BIZUNO_DATA."temp/$moduleID.zip", BIZUNO_EXT.$moduleID, false);
                if (file_exists(BIZUNO_EXT."$moduleID/bizunoUPG.php")) {
                    require(BIZUNO_EXT."$moduleID/bizunoUPG.php"); // handle any local db or file changes
                    unlink(BIZUNO_EXT."$moduleID/bizunoUPG.php");
                }
                dbClearCache();
                $layout = array_replace_recursive($layout, ['content'=>['action'=>'href','link'=>$this->BIZUNO_HOME."&p=bizuno/settings/manager"]]);
            } else {
                msgAdd('There was a problem retrieving your extension, please contact PhreeSoft for assistance.');
            }


It’s a simple copy directly from my server to your myFiles/temp folder. Please see if the destination folder is there. The file name you are looking for is xfrPhreeBooks.zip

If it is not there, check your php error log to see if your server configuration is preventing the copy command from an external URL.

Dave
