### ISSUE TITLE
Importing Sales and Purchase Orders

### ISSUE THREAD

**Issue by felsenstein** [phreebooks/PhreeBooksERP#259]
I'd be interested in testing importing sales and purchase orders under Modules-Import/Export/PhreeBooks Accounting, but couldn't find any documentation or sample files.  Is there somewhere this is posted that I missed?

Thank you for your help.

**Comment by phreesoft** [comment]
This should help. If you have any issues, let me know.

https://www.phreesoft.com/biz-school/?section=converting-from-another-app <https://www.phreesoft.com/biz-school/?section=converting-from-another-app>

Dave
