### ISSUE TITLE
[security] Unauthenticated Information Disclosure - Database Backups

### ISSUE THREAD

**Issue by bcoles** [phreebooks/PhreeBooksERP#260]
Database backups are accessible to unauthenticated users, provided that the correct file name can be guessed. Database backups include usernames and password hashes for phreebooks user accounts.

[IMAGE REMOVE BY MODERATOR FOR SECURITY REASONS]

**Comment by phreesoft** [comment]
Thanks for posting this issue. This exposure is reduced by disabling directory browsing on the host server which should be one of the first things in securing any server. It is still a security issue nonetheless. The project will address this in two ways, first by adding a dummy index.php file in the backups folder and second by disabling direct access to the myFiles folder.

The next release (3.2.5) will address this by forcing the dist.htaccess file included with the release to be renamed to .htaccess in the root folder if one is not present at time of install/upgrade. The rewrite engine will prevent any direct access to the myFiles folder or subfolders.

**Comment by bcoles** [comment]
A dummy `index.php` file would partially mitigate this issue by preventing directory indexing.

While the use of `.htaccess` in `PhreeBooks Release 5.2.8 w/Bizuno Library 3.2.5` is a good start, unfortunately this does not resolve the issue.

`.htaccess` is valid only for Apache web servers, and does not take effect unless Apache is configured with the [`AllowOverride`](https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride) directive. By default, this directive is disabled. For example, on a default install on Ubuntu 16.04.1:

```
grep -i AllowOverride /etc/apache2/apache2.conf 
	AllowOverride None
	AllowOverride None
	AllowOverride None
#	AllowOverride None
# for additional configuration directives.  See also the AllowOverride
```

I offer a few solutions:

* The installation instructions should mention the requirement to enable this directive.
  * Unfortunately, users may not have access to the HTTP server configuration on their hosting platform.
* The best way to resolve this issue is probably to store sensitive content (such as uploaded content, backups, and debug logs) outside of the web root directory.
  * Unfortunately, the web server would require read and write access to this directory, and users may not have access to the server filesystem to apply the appropriate filesystem permissions.
* Alternatively, uploaded content could be stored in the database.
  * This approach is not likely to be practical for backups and debug logs.
* Another option is to store the files using [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier) for file names. UUIDs are of sufficient complexity to resist brute-force attacks, which significantly decreases the likelihood of unauthorised remote access.
