### ISSUE TITLE
[security] Unauthenticated Information Disclosure - Directory Indexing

### ISSUE THREAD

**Issue by bcoles** [phreebooks/PhreeBooksERP#261]
By default, the contents of the `myFiles` directory are disclosed to unauthenticated users.

![myFiles](https://user-images.githubusercontent.com/434827/60431459-35bf9280-9c43-11e9-864d-520234a96c4d.png)

This is particularly problematic, as the contents of the `backups` directory are also disclosed, including usernames and password hashes, which are likewise accessible without authentication (#260).

![myFiles/backups](https://user-images.githubusercontent.com/434827/60431493-48d26280-9c43-11e9-80a1-4fd672cd53a1.png)

**Comment by phreesoft** [comment]
Thanks for posting this issue. This exposure is eliminated by disabling directory browsing on the host server which should be one of the first things in securing any server. It is still a security issue nonetheless. The project will address this by adding a .htaccess file in the root folder if one is not present to turn off directory browsing.

The next release (3.2.5) will address this by forcing the dist.htaccess file included with the release to be renamed to .htaccess in the root folder if one is not present at time of install/upgrade.

**Comment by bcoles** [comment]
A dummy `index.php` file would partially mitigate this issue by preventing directory indexing.

While the use of `.htaccess` in `PhreeBooks Release 5.2.8 w/Bizuno Library 3.2.5` is a good start, unfortunately this does not resolve the issue.

`.htaccess` is valid only for Apache web servers, and does not take effect unless Apache is configured with the [`AllowOverride`](https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride) directive. By default, this directive is disabled. For example, on a default install on Ubuntu 16.04.1:

```
grep -i AllowOverride /etc/apache2/apache2.conf 
	AllowOverride None
	AllowOverride None
	AllowOverride None
#	AllowOverride None
# for additional configuration directives.  See also the AllowOverride
```

I offer a few solutions:

* The installation instructions should mention the requirement to enable this directive.
  * Unfortunately, users may not have access to the HTTP server configuration on their hosting platform.
* The best way to resolve this issue is probably to store sensitive content (such as uploaded content, backups, and debug logs) outside of the web root directory.
  * Unfortunately, the web server would require read and write access to this directory, and users may not have access to the server filesystem to apply the appropriate filesystem permissions.
* Alternatively, uploaded content could be stored in the database.
  * This approach is not likely to be practical for backups and debug logs.
* Another option is to store the files using [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier) for file names. UUIDs are of sufficient complexity to resist brute-force attacks, which significantly decreases the likelihood of unauthorised remote access.
