### ISSUE TITLE
[security] Unauthenticated Path Traversal - Arbitary File Disclosure

### ISSUE THREAD

**Issue by bcoles** [phreebooks/PhreeBooksERP#263]
`bizunoFS.php` does not enforce authentication and is vulnerable to path traversal, permitting unauthenticated users to disclose arbitrary files from the server file system.

```
http://phreebooks.local/PhreeBooksERP/bizunoFS.php?&src=../../../../../../../../../etc/passwd
```

[IMAGE REMOVED BY MODERATOR FOR SECURITY REASONS]

**Comment by phreesoft** [comment]
Thanks for reporting this issue. the project will correct this in  release 3.2.5 by adding additional filtering (using php realpath function) and other filters to validate the destination path before allowing a file to be viewed. Additional filtering for to restrict certain extensions (currently images only) will be added so critical system files cannot be viewed as well as path must fall within the myFiles directory structure.
