### ISSUE TITLE
Enhancement: product Image upload

### ISSUE THREAD

**Issue by alvin101** [phreebooks/PhreeBooksERP#266]
When adding an image to a product you select the file and hit upload, but then you must search for the image and select it before you can use it. 

After you hit the upload button the image should automatically be selected...

**Comment by phreesoft** [comment]
I don’t want to add this functionality. I often upload several images at once and do not want them to be auto selected. Once the image is uploaded, all yo have to do is click it to select. That’s easy enough.

Dave
