### ISSUE TITLE
Ajax error

### ISSUE THREAD

**Issue by chazdiezal** [phreebooks/PhreeBooksERP#268]
Dave,

Any idea what may be going on with this error on install
![ajax error](https://user-images.githubusercontent.com/11147538/65723187-dd4e3480-e07b-11e9-8f43-49c58d4446c1.PNG)

**Comment by phreesoft** [comment]
The application didn’t install properly. I recommend you remove the tables from your db, delete the /bizunoCFG.php file and try to install again. If it fails a second time, make sure you have InnoDB enabled on your mysql server.

Dave
