### ISSUE TITLE
error posting journal

### ISSUE THREAD

**Issue by chazdiezal** [phreebooks/PhreeBooksERP#269]
Hi Dave,

I'm seeing an error in the trace log when trying to post a journal entry in 5.3.3.

Time: 8 ms, 5 SQLs 1.07 ms => /********* Posting Journal main ... id = 0 and journal_id = 2
Time: 8 ms, 5 SQLs 1.07 ms => Setting item defaults as part of a post.
Time: 8 ms, 5 SQLs 1.07 ms =>   Removing system generated gl rows. Started with 2 rows  and ended with 2 rows.
Time: 8 ms, 6 SQLs 1.24 ms => Finished executing action insert for SQL (in 0.00016710412597654 ms): INSERT INTO journal_main (`id`, `journal_id`, `store_id`, `recur_id`, `so_po_ref_id`, `invoice_num`, `sales_tax`, `total_amount`, `terms`, `gl_acct_id`, `currency`, `currency_rate`, `closed`, `waiting`, `post_date`, `terminal_date`, `period`, `admin_id`, `rep_id`, `contact_id_b`, `contact_id_s`, `description`, `address_id_b`, `primary_name_b`, `contact_b`, `address1_b`, `address2_b`, `city_b`, `state_b`, `postal_code_b`, `country_b`, `telephone1_b`, `email_b`, `drop_ship`, `discount`) VALUES ('0', '2', '0', '0', '0', 'GL000001', '0', '1', '2', '', 'USD', '1', '0', '0', '2019-09-30', '2019-09-30', '9', '1', '0', '0', '0', 'General Journal:  ...', '', 'bill\'s meats', '', '', '', '', '', '', 'USA', '', '', '', '0') returning result: row ID =
Time: 8 ms, 6 SQLs 1.24 ms => SQL Error: action: insert SQL (in 0.00016710412597654 ms): INSERT INTO journal_main (`id`, `journal_id`, `store_id`, `recur_id`, `so_po_ref_id`, `invoice_num`, `sales_tax`, `total_amount`, `terms`, `gl_acct_id`, `currency`, `currency_rate`, `closed`, `waiting`, `post_date`, `terminal_date`, `period`, `admin_id`, `rep_id`, `contact_id_b`, `contact_id_s`, `description`, `address_id_b`, `primary_name_b`, `contact_b`, `address1_b`, `address2_b`, `city_b`, `state_b`, `postal_code_b`, `country_b`, `telephone1_b`, `email_b`, `drop_ship`, `discount`) VALUES ('0', '2', '0', '0', '0', 'GL000001', '0', '1', '2', '', 'USD', '1', '0', '0', '2019-09-30', '2019-09-30', '9', '1', '0', '0', '0', 'General Journal:  ...', '', 'bill\'s meats', '', '', '', '', '', '', 'USA', '', '', '', '0') returned error:Array
(
    [0] => HY000
    [1] => 1366
    **[2] => Incorrect integer value: '' for column 'address_id_b' at row 1**
)

Time: 8 ms, 6 SQLs 1.24 ms => Adding to msgStack, level trap, msg: Database error posting main record, see trace!
Time: 9 ms, 6 SQLs 1.24 ms => entering dbWriteCache
Time: 9 ms, 6 SQLs 1.24 ms => Writing config table for module: phreebooks
Time: 9 ms, 7 SQLs 1.79 ms => Finished executing action update for SQL (in 0.0005540336151123 ms): UPDATE configuration SET `config_value`='{\"currency\":{\"default\":\"USD\",\"iso\":{\"USD\":{\"title\":\"United States Dollar\",\"code\":\"USD\",\"prefix\":\"$\",\"suffix\":\"\",\"dec_pt\":\".\",\"sep\":\",\",\"dec_len\":\"2\",\"pfxneg\":\"(\",\"sfxneg\":\")\",\"value\":1}},\"defISO\":\"USD\"},\"chart\":{\"accounts\":{\"1000\":{\"id\":\"1000\",\"type\":\"0\",\"cur\":\"USD\",\"title\":\"Cash\"},\"1020\":{\"id\":\"1020\",\"type\":\"0\",\"cur\":\"USD\",\"title\":\"Checking Account\"},\"1100\":{\"id\":\"1100\",\"type\":\"2\",\"cur\":\"USD\",\"title\":\"Accounts Receivable\"},\"1150\":{\"id\":\"1150\",\"type\":\"2\",\"cur\":\"USD\",\"title\":\"Allowance for Doubtful Debt\"},\"1200\":{\"id\":\"1200\",\"type\":\"4\",\"cur\":\"USD\",\"title\":\"Inventory\"},\"1400\":{\"id\":\"1400\",\"type\":\"6\",\"cur\":\"USD\",\"title\":\"Prepaid Expenses\"},\"1500\":{\"id\":\"1500\",\"type\":\"8\",\"cur\":\"USD\",\"title\":\"Property and Equipment\"},\"1900\":{\"id\":\"1900\",\"type\":\"10\",\"cur\":\"USD\",\"title\":\"Accum.

**Comment by phreesoft** [comment]
Make sure your database is not in strict mode.

Dave

**Comment by chazdiezal** [comment]
This worked perfectly, thanks Dave!
