### ISSUE TITLE
phpmailer missing class

### ISSUE THREAD

**Issue by lankeeyankee** [phreebooks/PhreeBooksERP#270]
When going to the password forgotten feature I get this error:

Bizuno Ajax Error: Expecting JSON, got HTML (you can probably ignore unless debugging), received:

<br /> <b>Fatal error</b>: require_once(): Failed opening required 'apps/PHPMailer/class.phpmailer.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in <b>/portal/mail.php</b> on line <b>33</b><br />

**Comment by lankeeyankee** [comment]
Looks like PHPMailer was reconfigured and no longer has that separate class file

**Comment by phreesoft** [comment]
You are right. I updated to the newest version of phpMailer and forgot to update the PhreeBooks 5 wrapper. 

I will update the /portal/mail/.php file to include the new phpMailer library in release 5.3.3.2.
