### ISSUE TITLE
cannot log back in

### ISSUE THREAD

**Issue by lankeeyankee** [phreebooks/PhreeBooksERP#271]
After logging out, I am unable to log back in, I keep getting the error The information you entered cannot be validated, please retry.

I am definitely using the password I entered when setting it up. Although the show password function is not working either on firefox. But I have deleted the install and emptied the DB and tried again several times with the same result. I can be in the admin when I first create the install but as soon as I log out it will not allow me to log back in

**Comment by phreesoft** [comment]
I get this every now and then. Enter both the username and password and press the delete key to clear any residual information.

Dave

**Comment by lankeeyankee** [comment]
Unfortunately, that did not work. I tried in in chrome, which I have never used to go to the install, and was able to log in once. I logged out and experienced the same issue. I did as you suggested on both browsers without success. I cleared cookies and cache, refreshed the page, and still get the same result. Not sure why this would happen for me and not you unless you are using something other than firefox or chrome?

**Comment by phreesoft** [comment]
Are you using PhreeBooks 5?

**Comment by phreesoft** [comment]
Did you upgrade today to 3.3.1?

**Comment by lankeeyankee** [comment]
Yes, I upgraded earlier today to 3.3.1. I am just using the files from this repo, do I need something else, too?

**Comment by lankeeyankee** [comment]
Nothing is showing in the console or logs, either.

**Comment by phreesoft** [comment]
try clearing your browser cache for the past 24 hours. I made some changes for security to prevent browser sniffing and this may cause the issue you are having.

Dave

**Comment by lankeeyankee** [comment]
OK, that seemed to be it. Although, both browsers want to keep the email in the field. It has to be cleared then manually typed in again otherwise it will not work. Is there a way to prevent browsers from retaining the email address to avoid any confusion for people?

**Comment by phreesoft** [comment]
Should be ok to have the email there. Make sure you backspace to clear the password as some browsers leave some residual in there.

Dave

**Comment by lankeeyankee** [comment]
yes, it's the backspacing/deleting that needs to happen every time in firefox

**Comment by phreesoft** [comment]
I’ll get that fixed in the next release. It doesn’t seem to do that in Chrome or Safari.

Dave

**Comment by lankeeyankee** [comment]
yes, it works every time now with 1 backspace and 1 delete. Glad you figured it out!
