### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by felsenstein** [phreebooks/PhreeBooksERP#272]
In order to get the attachments to work properly on the bottom of the Vendor, Purchase, and GL screens, I have to change my PHP version from 5.6 to 7.  Any idea why this might be?

If I have it set to 5.6 it will let me select a file but it won't upload it.  As soon as I change it to 7 it works fine.

**Comment by phreesoft** [comment]
Check your php error log, there might be a deprecated function I use. I haven’t tested with php 5.6 for several years.

Dave
